package com.tsi.sjumbe.demoTest;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchAndExistingDeleteReviewTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchAndExistingDeleteReview() {
    driver.get("http://3.81.24.215:3000/");
    driver.manage().window().setSize(new Dimension(1791, 1040));
    driver.findElement(By.cssSelector(".SearchBar > input")).click();
    driver.findElement(By.cssSelector(".SearchBar > input")).sendKeys("anacon");
    driver.findElement(By.name("Review ID")).click();
    driver.findElement(By.name("Review ID")).sendKeys("18");
    driver.findElement(By.cssSelector(".reviews")).click();
    driver.findElement(By.cssSelector(".reviews")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".reviews"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("Review ID")).click();
    driver.findElement(By.name("Review ID")).click();
    {
      WebElement element = driver.findElement(By.name("Review ID"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector("button:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".SearchBar > input")).click();
    driver.findElement(By.cssSelector(".SearchBar > input")).sendKeys("anaconda");
  }
}
