package com.tsi.sjumbe.demoTest;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

public class SearchAndAddNewMovieReviewTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchandaddnewmoviereview() {
    driver.get("http://3.81.24.215:3000/");
    driver.manage().window().setSize(new Dimension(1791, 1040));
    driver.findElement(By.cssSelector(".SearchBar > input")).click();
    driver.findElement(By.cssSelector(".SearchBar > input")).sendKeys("anaconda");
    driver.manage().timeouts().implicitlyWait(30000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector(".post > input:nth-child(1)")).click();
    driver.findElement(By.cssSelector(".post > input:nth-child(1)")).sendKeys("315");
    driver.manage().timeouts().implicitlyWait(30000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector(".post > input:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".post > input:nth-child(3)")).sendKeys("It was pretty good actually!!");
    driver.findElement(By.cssSelector(".post > input:nth-child(5)")).click();
    driver.findElement(By.cssSelector(".post > input:nth-child(5)")).sendKeys(" 4");
    driver.findElement(By.cssSelector(".post > button")).click();
    driver.manage().timeouts().implicitlyWait(30000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector(".SearchBar > input")).click();
    driver.manage().timeouts().implicitlyWait(30000, TimeUnit.MILLISECONDS);
    driver.findElement(By.cssSelector(".SearchBar > input")).sendKeys("ana");
  }
}
